version: "1.0"
info:
  model: int-scaffold
packages:
- name: VP_UAE_DEMO01Project
  gitServerName: VP_WMIO_GIT
  gitUrl: https://github.com/v1adp0s2-wmio
  gitUsername: v1adp0s2-wmio
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_1
  packages:
  - name: VP_UAE_DEMO01Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolable
  : "false"
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.dbType
  : MSSQL
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.keyStore
  : ""
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.serverName
  : poc-mssql
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.networkProtocol
  : ""
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionEnabled
  : "false"
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.user
  : sa
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.password
  : "{AES}3Q/DheX9dMA8VOnPUYxzL5UbwnlY3BVjnHcvc4175mk="
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.databaseName
  : wm-demo
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.portNumber
  : "1433"
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.trustStore
  : ""
  ? artConnection.VP_UAE_DEMO01Project.project.vp_uae_demo01.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupBackoffSecs
  : "10"
